### ISSUE TITLE
GraphQL: Cannot query field "alignments" on type "Monster"

### ISSUE THREAD

**Issue by khaosophy** [5e-bits/5e-srd-api#358]
I was looking for the monster alignment data, and found it in the REST API, but I'm not seeing it in the GraphQL (I tried `alignments` and `alignment`).

I can try to dig into this myself this week, but I wanted to post the issue first, in case I'm missing something obvious.

**Comment by fergcb** [comment]
This definitely looks like a legitimate flaw in the GraphQL schema. A PR would be most welcome!

**Comment by ecshreve** [comment]
ahh nice catch, poked around a bit and i think i have a handle on what's going on. this stems from `Monster` field definitions all being slightly different from the comparable `Race` and `Class` fields

for example, we have a [defintion for armor class](https://github.com/5e-bits/5e-srd-api/blob/6b53de0fa359c0723badb17d140bb784f0def6d8/src/graphql/typeDefs.graphql#L31)
```
type ArmorClass {
  base: Int!
  dex_bonus: Boolean!
  max_bonus: Int
}
```

and then we have the slightly different [monster variety](https://github.com/5e-bits/5e-srd-api/blob/6b53de0fa359c0723badb17d140bb784f0def6d8/src/graphql/typeDefs.graphql#L665)
```type MonsterArmorClass {
  type: MonsterArmorClassType!
  desc: String
  value: Int!
  armor: [Armor]
  spell: Spell
  condition: Condition
}
```

in the case of alignments, we [have a defnition](https://github.com/5e-bits/5e-srd-api/blob/6b53de0fa359c0723badb17d140bb784f0def6d8/src/graphql/typeDefs.graphql#L31) that returns an Alignment object, but if we look at the Monster schema in the database or the rest api, we can see that the `Monster.alignment` field is only a primitive string.

i think there's a couple options 
- add an enum definition for `MonsterAlignment`, and have the gql query for `monster.monster-alignment` return the simple string val
OR
- update the monster schema to return an Alignment 

i'm going to try and get a PR up for that first option this afternoon

**Comment by fergcb** [comment]
The second option definitely seems more appealing to me! There seems almost no point in having an Alignments collection if we don't reference it from Monster documents.

**Comment by ecshreve** [comment]
i lied a little bit by accident.

in the gql schema , we currently only return the `Alignment` object on root root queries, and from the `IdealOption` type.

in the current schema the alignment field on the `Race` type, a primitive string 🤔 going to think about this a little more

**Comment by ecshreve** [comment]
oh yeah i made it way more complicated than it was. we should be able to get the string exposed real easy, but if we want to return an Alignment object instead it's a bit more work

localhost
<img width="1512" alt="Screenshot 2023-07-21 at 2 57 31 PM" src="https://github.com/5e-bits/5e-srd-api/assets/1425775/9aa7879f-5cc7-4a58-a590-3115f192b80b">

**Comment by mlupton100** [comment]
It looks like the swagger openapi spec never caught up with this change which is tripping up a generated typescript client I've made 😢 

If it's a simple as updating `monster.yml` I'm happy to raise a PR to get this merged?

```yml
        alignments:
          description: "A creature's general moral and personal attitudes."
          type: string
          enum:
            - chaotic neutral
            - chaotic evil
            - chaotic good
            - lawful neutral
            - lawful evil
            - lawful good
            - neutral
            - neutral evil
            - neutral good
            - any alignment
            - unaligned
```
